#**Exercício 1-  Normalidade**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import shapiro
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:

np.random.seed(42)  # Garante a reprodutibilidade dos resultados
n_samples = 200  #


phi = 0.4  # Coeficiente Autoregressivo [AR(1)]
theta = 0.3  # Coeficiente de Média Móvel [MA(1)]
mu = 50.0  # Média constante da série


# Choques aleatórios rigorosamente extraídos de N(0, 1.5^2)
erros = np.random.normal(loc=0, scale=1.5, size=n_samples)

# Construção da equação de diferenças
y = np.zeros(n_samples)
y[0] = mu + erros[0]

for t in range(1, n_samples):
    y[t] = mu + phi * (y[t - 1] - mu) + erros[t] + theta * erros[t - 1]

# Organização dos dados em formato de Série Temporal Pandas
datas = pd.date_range(start='2025-01-01', periods=n_samples, freq='D')

In [ ]:
serie_A = pd.Series(y, index=datas, name='Serie  A')

In [ ]:
serie_A .head(10)

2025-01-01    50.745071
2025-01-02    50.314153
2025-01-03    51.034975
2025-01-04    52.989995
2025-01-05    51.530131
2025-01-06    50.155478
2025-01-07    52.325649
2025-01-08    52.792057
2025-01-09    50.757957
2025-01-10    50.905759
Freq: D, Name: Serie  A, dtype: float64

## **Itens exercício 1**

1. Plot a série temporal.
2. Plot o gráfico QQ-Plot Normal da série temproal.
3. Plot o histograma da série temporal.
4. Realize o teste de Shapiro Wilk. O que se conclui?

#**Exercício 2-  Normalidade**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import shapiro
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
np.random.seed(42)  # Garante a reprodutibilidade dos resultados
n_samples = 200


phi = 0.5  # Parâmetro AR(1)
theta = -0.3  # Parâmetro MA(1)
mu = 100.0  # Nível médio da série

# Choques extraídos de uma distribuição com forte assimetria à direita
ruido_exp = np.random.exponential(scale=2.0, size=n_samples)

# Centralização dos erros em média zero (mantedo a assimetria)
erros_nao_normais = ruido_exp - ruido_exp.mean()

# Construção da equação de diferenças do processo estocástico
y = np.zeros(n_samples)
y[0] = mu + erros_nao_normais[0]

for t in range(1, n_samples):
    y[t] = (
        mu
        + phi * (y[t - 1] - mu)
        + erros_nao_normais[t]
        + theta * erros_nao_normais[t - 1]
    )

# Estruturação em Pandas Series com índice temporal
datas = pd.date_range(start='2025-01-01', periods=n_samples, freq='D')
serie_b = pd.Series(y, index=datas, name='Serie b')

In [ ]:
serie_b.head(10)

2025-01-01     99.047563
2025-01-02    103.938783
2025-01-03    101.473129
2025-01-04    100.448721
2025-01-05     98.692164
2025-01-06     98.259818
2025-01-07     97.824148
2025-01-08    101.574951
2025-01-09    100.095220
2025-01-10    100.634980
Freq: D, Name: Serie b, dtype: float64

## **Itens exercício 2**

1. Plot a série temporal.
2. Plot o gráfico QQ-Plot Normal da série temproal.
3. Plot o histograma da série temporal.
4. Realize o teste de Shapiro Wilk. O que se conclui?