# **Exercício Sunspots**

Manchas solares são fenômenos temporários na fotosfera do Sol que aparecem como manchas mais escuras do que as áreas ao redor. Elas são regiões de temperatura superficial reduzida, causadas por concentrações de fluxo do campo magnético que inibem a convecção. As manchas solares geralmente aparecem em pares de polaridade magnética oposta. Seu número varia de acordo com o ciclo solar aproximado de 11 anos.


* **Item 1-** Relalize a analise exploratória dos dados
* **Item 2 -** Construa uma rede neural LSTM utilizando adequada janela de tempo a fim de prever as machas solares.

In [1]:
import pandas as pd
import numpy as np

# URL direto do dataset Sunspots
sunspots_url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/monthly-sunspots.csv"

# Carregar dados
sunspots_df = pd.read_csv(sunspots_url)
print("Sunspots Dataset:")
print(sunspots_df.head())
print(f"\n Dimensões: {sunspots_df.shape}")
print(f" Período: {sunspots_df['Month'].min()} até {sunspots_df['Month'].max()}")

Sunspots Dataset:
     Month  Sunspots
0  1749-01      58.0
1  1749-02      62.6
2  1749-03      70.0
3  1749-04      55.7
4  1749-05      85.0

 Dimensões: (2820, 2)
 Período: 1749-01 até 1983-12

In [2]:
sunspots_df.head(10)

     Month  Sunspots
0  1749-01      58.0
1  1749-02      62.6
2  1749-03      70.0
3  1749-04      55.7
4  1749-05      85.0
5  1749-06      83.5
6  1749-07      94.8
7  1749-08      66.3
8  1749-09      75.9
9  1749-10      75.5

In [3]:
sunspots_df.to_csv('sunspots.csv', encoding='utf-8', index=False)

In [4]:
sunspots_df2 = pd.read_csv('sunspots.csv')

In [5]:
sunspots_df2.head()

     Month  Sunspots
0  1749-01      58.0
1  1749-02      62.6
2  1749-03      70.0
3  1749-04      55.7
4  1749-05      85.0